-- Tabelas adaptadas para SQL Server
CREATE TABLE Users (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Cpf VARCHAR(11) UNIQUE NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    [Role] VARCHAR(20) CHECK ([Role] IN ('ADMIN', 'SELLER')) NOT NULL,
    CreatedAt DATETIME2 DEFAULT GETDATE()
);

CREATE TABLE Sellers (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE,
    Name VARCHAR(100) NOT NULL,
    Phone VARCHAR(20),
    Email VARCHAR(150), -- Adicionado para bater com o SellerMapper
    Active BIT DEFAULT 1,
    CreatedAt DATETIME2 DEFAULT GETDATE()
);

CREATE TABLE Customers (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    CompanyName VARCHAR(150) NOT NULL,
    Cnpj VARCHAR(14) UNIQUE NOT NULL,
    LatitudeTarget DECIMAL(12, 9) NOT NULL,
    LongitudeTarget DECIMAL(12, 9) NOT NULL,
    CreatedAt DATETIME2 DEFAULT GETDATE()
);

CREATE TABLE Checkins (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    SellerId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Sellers(Id) NOT NULL,
    CustomerId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Customers(Id) NOT NULL,
    LatitudeCaptured DECIMAL(12, 9) NOT NULL,
    LongitudeCaptured DECIMAL(12, 9) NOT NULL,
    DistanceMeters FLOAT NOT NULL,
    CheckinTimestamp DATETIME2 DEFAULT GETDATE(),
    CheckoutLatitude DECIMAL(12, 9),
    CheckoutLongitude DECIMAL(12, 9),
    CheckoutDistanceMeters FLOAT,
    CheckoutTimestamp DATETIME2,
    DurationMinutes INT
);